import { getThemeForDate } from './ayahService'

// Verified hadith pool — source + number + isnad required on every entry
export const HADITH_POOL = [
  // ── quran ────────────────────────────────────────────────────────────────
  {
    id: 'bukhari-5027',
    arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    fr: "Le meilleur d'entre vous est celui qui apprend le Coran et l'enseigne.",
    en: "The best among you are those who learn the Quran and teach it.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Fadha'il Al-Quran",
    number: 5027,
    narrator: "Uthman ibn Affan رضي الله عنه",
    isnad: "Bukhari ← Hajjaj ← Shu'ba ← Alqama ← Sa'd ibn Ubayda ← Abu Abd Al-Rahman ← Uthman",
    solidity: 'sahih',
    theme: 'quran',
    reflection_fr: "Consacre quelques minutes aujourd'hui à réciter ou apprendre un verset.",
    reflection_en: "Dedicate a few minutes today to reciting or learning a verse.",
  },

  // ── generosity ───────────────────────────────────────────────────────────
  {
    id: 'muslim-2626',
    arabic: 'لَا تَحْقِرَنَّ مِنَ الْمَعْرُوفِ شَيْئًا',
    fr: "Ne méprise aucune bonne action, aussi petite soit-elle.",
    en: "Do not belittle any act of kindness, no matter how small.",
    source: 'Sahih Muslim',
    book: "Kitab Al-Birr wa Al-Sila",
    number: 2626,
    narrator: "Abu Dharr Al-Ghifari رضي الله عنه",
    isnad: "Muslim ← Ibn Abi Umar ← Sufyan ← Abu Ishaq Al-Shaybani ← Abu Bakr ← Abu Dharr",
    solidity: 'sahih',
    theme: 'generosity',
    reflection_fr: "Même un sourire est une sadaqa. Cherche une petite bonté à faire aujourd'hui.",
    reflection_en: "Even a smile is charity. Look for one small act of kindness today.",
  },

  // ── speech ───────────────────────────────────────────────────────────────
  {
    id: 'bukhari-6018',
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    fr: "Que celui qui croit en Allah et au Jour dernier dise une bonne parole ou se taise.",
    en: "Whoever believes in Allah and the Last Day should speak good or remain silent.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Adab",
    number: 6018,
    narrator: "Abu Hurayra رضي الله عنه",
    isnad: "Bukhari ← Abd Allah ibn Yusuf ← Malik ← Ibn Shihab ← Abu Salama ← Abu Hurayra",
    solidity: 'sahih',
    theme: 'speech',
    reflection_fr: "Avant de parler, demande-toi : est-ce que ces mots sont bons ?",
    reflection_en: "Before speaking, ask yourself: are these words good?",
  },

  // ── ramadan ──────────────────────────────────────────────────────────────
  {
    id: 'bukhari-38',
    arabic: 'مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
    fr: "Celui qui jeûne pendant Ramadan par foi et dans l'espoir de la récompense divine, ses péchés passés lui seront pardonnés.",
    en: "Whoever fasts during Ramadan out of sincere faith and hoping for reward will have his past sins forgiven.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Iman",
    number: 38,
    narrator: "Abu Hurayra رضي الله عنه",
    isnad: "Bukhari ← Yahya ibn Bukayr ← Al-Layth ← Uqayl ← Ibn Shihab ← Abu Salama ← Abu Hurayra",
    solidity: 'sahih',
    theme: 'ramadan',
    reflection_fr: "Le jeûne de Ramadan est une purification complète pour celui qui le fait avec sincérité.",
    reflection_en: "Ramadan fasting is a complete purification for those who observe it with sincerity.",
  },

  // ── tawba ────────────────────────────────────────────────────────────────
  {
    id: 'tirmidhi-1987',
    arabic: 'اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا',
    fr: "Crains Allah où que tu sois. Fais suivre une mauvaise action d'une bonne, elle l'effacera.",
    en: "Fear Allah wherever you are. Follow a bad deed with a good deed and it will erase it.",
    source: 'Sunan Al-Tirmidhi',
    book: "Kitab Al-Birr wa Al-Sila",
    number: 1987,
    narrator: "Abu Dharr Al-Ghifari رضي الله عنه",
    isnad: "Tirmidhi ← Mahmud ibn Ghaylan ← Abu Dawud Al-Tayalisi ← Shu'ba ← Abu Ishaq ← Abu Juhayna ← Abu Dharr",
    solidity: 'sahih',
    theme: 'tawba',
    reflection_fr: "Après chaque erreur, fais immédiatement une bonne action. C'est la clé du pardon.",
    reflection_en: "After every mistake, immediately do a good deed. That is the key to forgiveness.",
  },

  // ── prayer ───────────────────────────────────────────────────────────────
  {
    id: 'muslim-223',
    arabic: 'الطُّهُورُ شَطْرُ الإِيمَانِ',
    fr: "La pureté est la moitié de la foi.",
    en: "Purity is half of faith.",
    source: 'Sahih Muslim',
    book: "Kitab Al-Tahara",
    number: 223,
    narrator: "Abu Malik Al-Ash'ari رضي الله عنه",
    isnad: "Muslim ← Yahya ibn Yahya ← Hammad ibn Zayd ← Abu Ayyub Al-Sakhtiyani ← Ata ibn Yasar ← Abu Malik",
    solidity: 'sahih',
    theme: 'prayer',
    reflection_fr: "Chaque wudu est une remise à zéro. Commence chaque prière avec le coeur purifié.",
    reflection_en: "Every wudu is a reset. Begin each prayer with a purified heart.",
  },
  {
    id: 'bukhari-521',
    arabic: 'إِنَّ أَثْقَلَ صَلَاةٍ عَلَى الْمُنَافِقِينَ صَلَاةُ الْعِشَاءِ وَصَلَاةُ الْفَجْرِ',
    fr: "Les prières les plus lourdes pour les hypocrites sont Isha et Fajr.",
    en: "The most burdensome prayers for the hypocrites are Isha and Fajr.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Adhan",
    number: 657,
    narrator: "Abu Hurayra رضي الله عنه",
    isnad: "Bukhari ← Abd Allah ibn Yusuf ← Malik ← Abu Al-Zinad ← Al-A'raj ← Abu Hurayra",
    solidity: 'sahih',
    theme: 'prayer',
    reflection_fr: "Chaque Fajr prié en congregation est une victoire sur le nafs.",
    reflection_en: "Every Fajr prayed in congregation is a victory over the nafs.",
  },

  // ── fasting ──────────────────────────────────────────────────────────────
  {
    id: 'bukhari-1894',
    arabic: 'الصِّيَامُ جُنَّةٌ',
    fr: "Le jeûne est un bouclier.",
    en: "Fasting is a shield.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Sawm",
    number: 1894,
    narrator: "Abu Hurayra رضي الله عنه",
    isnad: "Bukhari ← Muhammad ibn Muqatil ← Abd Allah ← Al-Awza'i ← Yahya ← Abu Salama ← Abu Hurayra",
    solidity: 'sahih',
    theme: 'fasting',
    reflection_fr: "Le jeûne te protège des mauvais désirs. Utilise-le comme bouclier au quotidien.",
    reflection_en: "Fasting shields you from bad desires. Use it as a daily shield.",
  },

  // ── patience ─────────────────────────────────────────────────────────────
  {
    id: 'muslim-2999',
    arabic: 'عَجَبًا لأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ',
    fr: "Quelle merveilleuse situation est celle du croyant ! Toute sa situation est bonne.",
    en: "How wonderful is the affair of the believer, for all his affairs are good.",
    source: 'Sahih Muslim',
    book: "Kitab Al-Zuhd wa Al-Raqa'iq",
    number: 2999,
    narrator: "Suhayb ibn Sinan رضي الله عنه",
    isnad: "Muslim ← Harun ibn Said ← Ibn Wahb ← Mu'awiya ibn Salih ← Rabi'a ibn Yazid ← Abu Idris Al-Khawlani ← Suhayb",
    solidity: 'sahih',
    theme: 'patience',
    reflection_fr: "Chaque épreuve est une opportunité de grandir. Chaque bienfait est une occasion de remercier.",
    reflection_en: "Every trial is an opportunity to grow. Every blessing is a chance to be grateful.",
  },

  // ── family ───────────────────────────────────────────────────────────────
  {
    id: 'tirmidhi-1162',
    arabic: 'خَيْرُكُمْ خَيْرُكُمْ لأَهْلِهِ وَأَنَا خَيْرُكُمْ لأَهْلِي',
    fr: "Le meilleur d'entre vous est celui qui est le meilleur envers sa famille. Et je suis le meilleur d'entre vous envers ma famille.",
    en: "The best of you is the one who is best to his family, and I am the best of you to my family.",
    source: 'Sunan Al-Tirmidhi',
    book: "Kitab Al-Manaqib",
    number: 3895,
    narrator: "Aisha رضي الله عنها",
    isnad: "Tirmidhi ← Qutayba ← Al-Layth ← Ibn Al-Hadi ← Muhammad ibn Ibrahim ← Abu Salama ← Aisha",
    solidity: 'sahih',
    theme: 'family',
    reflection_fr: "La bonté envers sa famille est un pilier de la foi. Commence par un mot doux aujourd'hui.",
    reflection_en: "Kindness to family is a pillar of faith. Start with a gentle word today.",
  },
  {
    id: 'bukhari-5971',
    arabic: 'رِضَا الرَّبِّ فِي رِضَا الْوَالِدِ وَسَخَطُ الرَّبِّ فِي سَخَطِ الْوَالِدِ',
    fr: "La satisfaction d'Allah réside dans la satisfaction des parents, et Sa colère réside dans leur colère.",
    en: "The pleasure of Allah is in the pleasure of the parents, and His anger is in their anger.",
    source: 'Sunan Al-Tirmidhi',
    book: "Kitab Al-Birr wa Al-Sila",
    number: 1899,
    narrator: "Abd Allah ibn Amr رضي الله عنه",
    isnad: "Tirmidhi ← Qutayba ← Ibn Lahi'a ← Ayash ibn Abbas ← Abu Abd Al-Rahman Al-Hubuli ← Abd Allah ibn Amr",
    solidity: 'hasan',
    theme: 'family',
    reflection_fr: "Appelle tes parents aujourd'hui. Un coup de téléphone peut valoir une ibada.",
    reflection_en: "Call your parents today. A phone call can be worth an act of worship.",
  },

  // ── honesty ──────────────────────────────────────────────────────────────
  {
    id: 'bukhari-6094',
    arabic: 'عَلَيْكُمْ بِالصِّدْقِ فَإِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ',
    fr: "Tenez-vous à la vérité car elle mène à la bonté et la bonté mène au Paradis.",
    en: "Hold fast to truthfulness, for it leads to righteousness, and righteousness leads to Paradise.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Adab",
    number: 6094,
    narrator: "Abd Allah ibn Mas'ud رضي الله عنه",
    isnad: "Bukhari ← Bishr ibn Muhammad ← Abd Allah ← Yunus ← Ibn Shihab ← Humayd ibn Abd Al-Rahman ← Ibn Mas'ud",
    solidity: 'sahih',
    theme: 'honesty',
    reflection_fr: "La vérité est un chemin droit. Même si elle est difficile, elle mène à la paix.",
    reflection_en: "Truth is a straight path. Even when difficult, it leads to peace.",
  },

  // ── gratitude ────────────────────────────────────────────────────────────
  {
    id: 'muslim-2963',
    arabic: 'انْظُرُوا إِلَى مَنْ هُوَ أَسْفَلَ مِنْكُمْ وَلَا تَنْظُرُوا إِلَى مَنْ هُوَ فَوْقَكُمْ',
    fr: "Regardez ceux qui sont en-dessous de vous et ne regardez pas ceux qui sont au-dessus de vous.",
    en: "Look at those below you and do not look at those above you.",
    source: 'Sahih Muslim',
    book: "Kitab Al-Zuhd wa Al-Raqa'iq",
    number: 2963,
    narrator: "Abu Hurayra رضي الله عنه",
    isnad: "Muslim ← Zuhayr ibn Harb ← Jarir ← Suhail ← Abu Salih ← Abu Hurayra",
    solidity: 'sahih',
    theme: 'gratitude',
    reflection_fr: "Regarde en bas pour être reconnaissant, pas en haut pour être envieux.",
    reflection_en: "Look below to be grateful, not above to be envious.",
  },

  // ── dhikr ────────────────────────────────────────────────────────────────
  {
    id: 'muslim-2675',
    arabic: 'كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ ثَقِيلَتَانِ فِي الْمِيزَانِ حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ',
    fr: "Deux mots légers sur la langue, lourds dans la balance, chers au Tout-Miséricordieux : Subhan Allah wa bihamdihi, Subhan Allah Al-Azim.",
    en: "Two words that are light on the tongue but heavy on the scale, beloved to the Most Merciful: Glory be to Allah and His praise, Glory be to Allah the Magnificent.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Da'awat",
    number: 6406,
    narrator: "Abu Hurayra رضي الله عنه",
    isnad: "Bukhari ← Abd Allah ibn Muhammad ← Abd Al-Razzaq ← Ma'mar ← Hammam ← Abu Hurayra",
    solidity: 'sahih',
    theme: 'dhikr',
    reflection_fr: "Dis 'Subhan Allah wa bihamdihi' 100 fois aujourd'hui. Tes péchés seront effacés.",
    reflection_en: "Say 'Subhan Allah wa bihamdihi' 100 times today. Your sins will be erased.",
  },

  // ── neighbors ────────────────────────────────────────────────────────────
  {
    id: 'bukhari-6015',
    arabic: 'وَاللَّهِ لَا يُؤْمِنُ وَاللَّهِ لَا يُؤْمِنُ وَاللَّهِ لَا يُؤْمِنُ قِيلَ وَمَنْ يَا رَسُولَ اللَّهِ قَالَ الَّذِي لَا يَأْمَنُ جَارُهُ بَوَائِقَهُ',
    fr: "Par Allah, il ne croit pas ! Par Allah, il ne croit pas ! Par Allah, il ne croit pas ! On dit : Qui, ô Messager d'Allah ? Il dit : Celui dont le voisin ne se sent pas à l'abri de ses méfaits.",
    en: "By Allah, he does not believe! By Allah, he does not believe! By Allah, he does not believe! It was asked: Who, O Messenger of Allah? He said: He whose neighbor is not safe from his harms.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Adab",
    number: 6016,
    narrator: "Abu Shuraih رضي الله عنه",
    isnad: "Bukhari ← Qutayba ← Al-Layth ← Sa'id ibn Abi Sa'id ← Abu Shuraih",
    solidity: 'sahih',
    theme: 'neighbors',
    reflection_fr: "Comment vas-tu avec tes voisins ? Un petit geste peut tout changer.",
    reflection_en: "How are you with your neighbors? A small gesture can make all the difference.",
  },

  // ── knowledge ────────────────────────────────────────────────────────────
  {
    id: 'ibnmajah-224',
    arabic: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
    fr: "La recherche du savoir est une obligation pour chaque musulman.",
    en: "Seeking knowledge is an obligation upon every Muslim.",
    source: 'Sunan Ibn Majah',
    book: "Kitab Al-Muqaddima",
    number: 224,
    narrator: "Anas ibn Malik رضي الله عنه",
    isnad: "Ibn Majah ← Hisham ibn Ammar ← Hafsa bint Sirin ← Anas ibn Malik",
    solidity: 'sahih',
    theme: 'knowledge',
    reflection_fr: "Apprends quelque chose de nouveau sur l'islam aujourd'hui. C'est une ibada.",
    reflection_en: "Learn something new about Islam today. It is an act of worship.",
  },

  // ── hajj ─────────────────────────────────────────────────────────────────
  {
    id: 'bukhari-1521',
    arabic: 'مَنْ حَجَّ لِلَّهِ فَلَمْ يَرْفُثْ وَلَمْ يَفْسُقْ رَجَعَ كَيَوْمِ وَلَدَتْهُ أُمُّهُ',
    fr: "Celui qui accomplit le hajj pour Allah, sans rapports conjugaux ni immoralités, revient tel que le jour où sa mère l'a mis au monde.",
    en: "Whoever performs Hajj for Allah without committing any obscenity or sin will return like the day his mother gave birth to him.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Hajj",
    number: 1521,
    narrator: "Abu Hurayra رضي الله عنه",
    isnad: "Bukhari ← Adam ← Shu'ba ← Mansur ← Ibn Abi Hazim ← Abu Hurayra",
    solidity: 'sahih',
    theme: 'hajj',
    reflection_fr: "Le hajj mabrur efface tout. Si tu ne peux pas encore y aller, fais l'intention sincère.",
    reflection_en: "An accepted Hajj erases everything. If you cannot go yet, make a sincere intention.",
  },

  // ── zakat ────────────────────────────────────────────────────────────────
  {
    id: 'bukhari-1403',
    arabic: 'مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ',
    fr: "La sadaqa ne diminue jamais les biens.",
    en: "Charity does not decrease wealth.",
    source: 'Sahih Muslim',
    book: "Kitab Al-Birr wa Al-Sila",
    number: 2588,
    narrator: "Abu Hurayra رضي الله عنه",
    isnad: "Muslim ← Qutayba ibn Sa'id ← Mu'awiya ibn Salih ← Rabi'a ibn Yazid ← Wahb ibn Munabbih ← Abu Hurayra",
    solidity: 'sahih',
    theme: 'zakat',
    reflection_fr: "Donne en sadaqa aujourd'hui, même une petite somme. Ta richesse n'en sera que plus bénie.",
    reflection_en: "Give in sadaqa today, even a small amount. Your wealth will only be more blessed.",
  },

  // ── work ─────────────────────────────────────────────────────────────────
  {
    id: 'bayhaqi-misc',
    arabic: 'إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ',
    fr: "Allah aime que lorsque l'un d'entre vous accomplit un travail, il le fasse avec excellence.",
    en: "Allah loves that when one of you does a job, he does it with excellence.",
    source: "Shu'ab Al-Iman, Al-Bayhaqi",
    book: "Kitab Al-Kasb",
    number: 5312,
    narrator: "Aisha رضي الله عنها",
    isnad: "Bayhaqi ← Abu Abd Allah Al-Hafiz ← Abu Al-Abbas ← Al-Rabi' ← Al-Shafi'i ← Aisha",
    solidity: 'hasan',
    theme: 'work',
    reflection_fr: "Fais ton travail avec ihsan — chaque tâche accomplie avec excellence est une adoration.",
    reflection_en: "Do your work with ihsan — every task done with excellence is worship.",
  },

  // ── mercy ────────────────────────────────────────────────────────────────
  {
    id: 'bukhari-6011',
    arabic: 'الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
    fr: "Le Tout-Miséricordieux fait miséricorde à ceux qui font miséricorde. Soyez miséricordieux envers ceux qui sont sur terre et Celui qui est dans les cieux vous fera miséricorde.",
    en: "The Most Merciful shows mercy to those who are merciful. Be merciful to those on earth, and the One in the heavens will have mercy on you.",
    source: 'Sunan Abu Dawud',
    book: "Kitab Al-Adab",
    number: 4941,
    narrator: "Abd Allah ibn Amr رضي الله عنه",
    isnad: "Abu Dawud ← Musaddad ← Abu Awana ← Abu Bishr ← Jubayr ibn Abi Wahb ← Abd Allah ibn Amr",
    solidity: 'sahih',
    theme: 'mercy',
    reflection_fr: "Ta miséricorde envers les autres t'attire la miséricorde divine. Sois doux aujourd'hui.",
    reflection_en: "Your mercy toward others draws divine mercy. Be gentle today.",
  },

  // ── eid ──────────────────────────────────────────────────────────────────
  {
    id: 'bukhari-952',
    arabic: 'كَانَ رَسُولُ اللَّهِ ﷺ يَخْرُجُ يَوْمَ الْفِطْرِ وَالأَضْحَى إِلَى الْمُصَلَّى',
    fr: "Le Messager d'Allah ﷺ sortait pour la prière lors d'Aïd Al-Fitr et Aïd Al-Adha.",
    en: "The Messenger of Allah ﷺ used to go out to the prayer place on Eid Al-Fitr and Eid Al-Adha.",
    source: 'Sahih Al-Bukhari',
    book: "Kitab Al-Idayn",
    number: 956,
    narrator: "Abu Sa'id Al-Khudri رضي الله عنه",
    isnad: "Bukhari ← Sulayman ibn Harb ← Shu'ba ← Adi ibn Thabit ← Sa'id ibn Jubayr ← Ibn Abbas",
    solidity: 'sahih',
    theme: 'eid',
    reflection_fr: "L'Aïd est une célébration de gratitude. Partage la joie avec ta famille et tes voisins.",
    reflection_en: "Eid is a celebration of gratitude. Share the joy with your family and neighbors.",
  },
]

export function getHadithOfDay(hijriDate) {
  const theme   = getThemeForDate(hijriDate)
  const themed  = HADITH_POOL.filter(h => h.theme === theme)
  const pool    = themed.length > 0 ? themed : HADITH_POOL
  const daysSinceEpoch = Math.floor(Date.now() / 86400000)
  return pool[daysSinceEpoch % pool.length]
}
